title: HEP — The Sacred Pou of Evolutionary Integrity
description: Non-bypassable rhythms, specs, and schemas for sovereignty-first AI (HEP–SIS).
remote_theme: just-the-docs/just-the-docs
search_enabled: true
search:
  heading_level: 3
  previews: 3
  rel_url: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
aux_links:
  "GitHub repository":
    - "https://github.com/MakaraNZ/hep-sacred-pou-evolutionary-integrity"
